### ISSUE TITLE
Update SA permissions 

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console-smoke-test#24]
Currently we are using the default service account, but this will probably not have the perms we need to test everything we want.  Will likely need to create a new SA & add the roles we need to do the appropriate testing.

**Comment by benjaminapetersen** [comment]
@enj may ping you for further info on this.

**Comment by jhadvig** [comment]
should be covered in https://github.com/openshift/openshift-ansible/pull/7880 although not really sure we need to create a special SA and add roles to it for the testing, at least not sure why?

**Comment by benjaminapetersen** [comment]
Ah, hadn't see that. taking a look now.

**Comment by benjaminapetersen** [comment]
I think it depends on the kinds of tests we expand to. I believe the thinking was that if we need to request certain things from the API && the default SA doesn't have access, we may need to tweak.

**Comment by benjaminapetersen** [comment]
At this point we haven't needed this.  I'm dropping the blocker tag... we may not need to do anything until (or if) we add addional specific tests that require additional permissions.
