### ISSUE TITLE
Test fails when obtaining self-sign certificates went wrong

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-web-console-smoke-test#31]
We should have a flag(or some kind of mechanism) that would turn on/off obtaining self-sign certificates cause for online we dont need to obtain them. In case we need it would be good to know if obtaining them fails for some reason.
@benjaminapetersen

**Comment by benjaminapetersen** [comment]
I just noticed this while running locally:

![screen shot 2018-04-12 at 12 07 08 pm](https://user-images.githubusercontent.com/280512/38689740-5dce6c86-3e4a-11e8-8b64-303734a5bdf0.png)

**Comment by benjaminapetersen** [comment]
Might be relevant... or not. I think this time I did an `oc cluster up` without a public hostname, so its running on `https://127.0.0.1:8443`.  Prob a hangup.

**Comment by jhadvig** [comment]
this is really weird.. cause when I dont specify the `--public-hostname` and then console binds to localhost I see the same issue. If I bind to a IP then everything works...but not sure why we see this
