### ISSUE TITLE
Host image on quay.io

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console-smoke-test#39]
The image should likely be moved to `quay.io` from `hub.docker.com` where our other images are.  It should also live under the `openshift` org, though I don't know if that is currently how things work given: https://quay.io/search?q=openshift

@jhadvig @spadgett

**Comment by benjaminapetersen** [comment]
Related to #17, this repository should probably live under `openshift` org on `github.com` as a first move.

**Comment by benjaminapetersen** [comment]
Tested this with a push to quay.io:

https://quay.io/repository/benjaminapetersen/web-console-smoke-test

Per convo with @ironcladlou, doesn't sound like we have an openshift org setup in quay yet, so final location is tbd.

**Comment by ironcladlou** [comment]
Got some clarity here. We can do manual pushes to quay.io/openshift, and those pushes must be gated by Clayton. Please reach out to him when you need to push a build for now.

**Comment by jhadvig** [comment]
cc'ing @smarterclayton

**Comment by benjaminapetersen** [comment]
&& a little more detail, for records.  ATM, we don't have a `quay.io/openshift` org, but we do have a `quay.io/redhat` org.  We have an image at https://quay.io/repository/redhat/origin-web-console-smoke-test?tab=info & can definitely put this wherever it needs to be when we are ready to use it.

**Comment by ironcladlou** [comment]
quay.io/redhat was a mistake (on my part) and needs removed

**Comment by ironcladlou** [comment]
or I should say, our images should be removed from quay.io/redhat- I don't control the repo itself.

**Comment by benjaminapetersen** [comment]
I can remove it, or at least make it private for now until we know if we will have an `openshift` org & easily move it.

**Comment by smarterclayton** [comment]
We have an openshift org.  You must request repos be created under it like we would for dockerhub

**Comment by smarterclayton** [comment]
I’ll be managing the move of individual components if you are already on the hub.

**Comment by jhadvig** [comment]
So we have two repos under the `redhat` org in quay:
- openshift-monitor-project-lifecycle
- origin-web-console-smoke-test

Would be awesome if you could migrate them under `openshift` orgranisation. Please let me know when its done so I can do appropriate changes in `openshift-ansbil` repo, where we are using those images.
Thanks !
